# Generated by Django 5.2.6 on 2025-09-12 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carreras", "0001_initial"),
        ("materias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pensum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semestre", models.PositiveIntegerField()),
                ("es_electiva", models.BooleanField(default=False)),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pensums",
                        to="carreras.carrera",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materias.materia",
                    ),
                ),
            ],
            options={
                "unique_together": {("carrera", "materia")},
            },
        ),
    ]
